### ISSUE TITLE
Referencing assets in CSS

### ISSUE THREAD

**Issue by ryanb** [rails/cssbundling-rails#22]
Is it possible to reference other assets such as images and fonts in CSS? In the asset pipeline you'd normally do `image-url("image.png")`, but from my understanding that is handled by `sass-rails` and requires an `scss` file.

Is there a recommended way for doing this through `cssbundling-rails` and the asset pipeline?

Thanks for your work on this gem!

**Comment by rmacklin** [comment]
Are you using PostCSS to process your CSS? If so, can https://github.com/postcss/postcss-url solve your use case?

**Comment by chloerei** [comment]
I try to add a postprocessor to replace asset path:

```ruby
class AssetUrlProcessor
  def self.call(input)
    context = input[:environment].context_class.new(input)

    data = input[:data].gsub(/url\((.+?)\)/) do |match|
      path = context.asset_path($1)
      "url(#{path})"
    end

    { data: data }
  end
end

Sprockets.register_postprocessor 'text/css', AssetUrlProcessor
```

Need an official solution.

**Comment by dhh** [comment]
Yes, we need an official solution to this. That asset url processor looks in the ballpark. Here's the one from sassy-rails: https://github.com/sass/sassc-rails/blob/master/lib/sassc/rails/functions.rb

**Comment by deepj** [comment]
I have a bit different "ask" for official solution. but I guess still related to this. How to reference and "import" assets from npm packages (in my case font-awesome). Here is how to do it in Phoenix/esbuild/sass https://gist.github.com/ks2211/75af6cddc051f5e261a29fc25eed5789

It would be wonderful some official solution for Rails 7/cssbuilding-rails

**Comment by stevestmartin** [comment]
> I try to add a postprocessor to replace asset path:
> 
> ```ruby
> class AssetUrlProcessor
>   def self.call(input)
>     # don't know why, copy from other processor
>     context = input[:environment].context_class.new(input)
> 
>     data = input[:data].gsub(/url\((.+?)\)/) do |match|
>       path = context.asset_path($1)
>       "url(#{path})"
>     end
> 
>     { data: data }
>   end
> end
> 
> Sprockets.register_postprocessor 'text/css', AssetUrlProcessor
> ```
> 
> It works for me. Need an official solution.

This works great, just ran into this.

**Comment by stevestmartin** [comment]
Updating to better handle asset URLs that contain quotes or if they use a data URI / full URL so that we do not attempt to overwrite with a wrong value.

Thanks for the starting point @chloerei 

_config/initializers/assets.rb_

```ruby
class AssetUrlProcessor
  def self.call(input)
    # don't know why, copy from other processor
    context = input[:environment].context_class.new(input)
    data = input[:data].gsub(/url\(["']?(.+?)["']?\)/i) do |match|
      if $1 !~ /(data:|http)/i
        path = context.asset_path($1)
        "url(#{path})"
      else
        "url(#{match})"
      end
    end

    { data: data }
  end
end

Sprockets.register_postprocessor 'text/css', AssetUrlProcessor

```

**Comment by ryanb** [comment]
Thanks for the feedback everyone. I ended up going with a post processor that uses `asset-url()` so that it doesn't conflict with other urls such as in node modules.

```
# config/initializers/asset_url_processor.rb
class AssetUrlProcessor
  def self.call(input)
    context = input[:environment].context_class.new(input)
    data = input[:data].gsub(/asset\-url\(["']?(.+?)["']?\)/) do |_match|
      "url(#{context.asset_path($1)})"
    end
    {data: data}
  end
end

Sprockets.register_postprocessor "text/css", AssetUrlProcessor
```

Keep in mind this only handles assets that are managed by sprockets. If we have other external assets that need to be included (such as within node modules), we could use postcss-url as @rmacklin mentioned. I'd probably configure it to output directly to `public/assets` so that it bypasses sprockets.

**Comment by stevestmartin** [comment]
Looks like [Propshaft](https://github.com/rails/propshaft) might be the official solution to this, although it seems to use an `asset-path` CSS function which mimics sprockets and @ryanb 's solution. However looking at @chloerei 's solution with minor improvements, I do like the idea that you could take a theme or library etc.. drop its assets into your assets_path and it just fixes everything without having to edit the CSS files to insert the `asset-path` calls, inevitably you always miss one. 

This would make drop in updates of themes, libraries, or icon fonts much simpler by just copying files into folders under `config.assets.paths` I would assume we could just add path's from `node_modules` here as well.

**Comment by ryanb** [comment]
@stevestmartin thanks for pointing out Propshaft. I replied to your issue there: https://github.com/rails/propshaft/issues/1

**Comment by Petercopter** [comment]
I think I'm running into this problem with FontAwesome. I've got a Rails 6.x app, and I switched from Webpacker to cssbundling-rails and jsbundling-rails. Everything is working great locally as far as I can tell. Compilation is SUPER fast, and there's a LOT less JavaScript involved in the entire process.

I pushed to Heroku, and it seems the font URLs aren't being rewritten. Not a problem, this application isn't live yet, so I get to play with the new and shiny with limited consequences.

Will Propshaft be the right solution for Rails 6.x apps? I see it's locked to Rails 7 right now.

**Comment by ryanb** [comment]
@Petercopter if the fonts are working in development but not production, they might not be included in the precompile. Try running `rails assets:precompile` and see if they are in the `public/assets` directory. If not, add them to the `app/assets/config/manifest.js` file similar to the images.

If they are included, you might need a post processor to remap the url, similar to the ones mentioned earlier.

**Comment by g1eyd50n** [comment]
I don't know why, but after that my saas compilation is breaking:
in this case it's in the _bootstrap.scss_

```
SassC::SyntaxError: Error: Invalid CSS after "...svg xmlns='http": expected expression (e.g. 1px, bold), was "://www.w3.org/2000/"
        on line 2350:66 of stdin
>> ('assets/data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBo
   ------------------------------------------^
```

```
.form-check-input:checked[type=radio] {
  background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='-4 -4 8 8'%3e%3ccircle r='2' fill='%23fff'/%3e%3c/svg%3e");
}
```

**Comment by ryanb** [comment]
@jcoyne thanks, I'll update it.

**Comment by dhh** [comment]
Solved via https://github.com/rails/sprockets-rails/pull/476. Thanks @jcoyne 🙏

**Comment by MrHubble** [comment]
@Petercopter were you able to get font awesome deploying correctly to Heroku? If yes, what did you use in your `manifest.js`?

**Comment by Petercopter** [comment]
@MrHubble Yes! I added this to my `manifest.js`
```
//= link_tree ../../../node_modules/@fortawesome/fontawesome-free/webfonts
```

**Comment by itsyoshio** [comment]
> @MrHubble Yes! I added this to my `manifest.js`
> 
> ```
> //= link_tree ../../../node_modules/@fortawesome/fontawesome-free/webfonts
> ```

Not directly related to the topic at hand, but what did you do to get the webfonts in dev?\
I tried working with postcss-url to rebase the path in the generated application.css, but it works in neither env.

**Comment by itsyoshio** [comment]
> MrHubble Yes! I added this to my `manifest.js`
> 
> ```
> //= link_tree ../../../node_modules/@fortawesome/fontawesome-free/webfonts
> ```

@Petercopter Not directly related to the topic at hand, but what did you do to get the webfonts in dev?\
I tried working with postcss-url to rebase the path in the generated application.css, but it works in neither env.

**Comment by ianheggie** [comment]
> > MrHubble Yes! I added this to my `manifest.js`
> > ```
> > //= link_tree ../../../node_modules/@fortawesome/fontawesome-free/webfonts
> > ```
> 
> @Petercopter Not directly related to the topic at hand, but what did you do to get the webfonts in dev? I tried working with postcss-url to rebase the path in the generated application.css, but it works in neither env.

@itsyoshio - I added the following to `config/initializers/assets.rb` and that fixed up the dev side.
`
Rails.application.config.assets.paths << Rails.root.join("node_modules/@fortawesome/fontawesome-free/webfonts")
`

For context, this was in addition to

- adding the link_tree command above in `app/assets/config/manifest.js`
- removing `gem "sassc-rails"` from `Gemfile` since `cssbundling-rails` can use `node_modules/.bin/sass`. The sass npm module is required by the bootstrap npm module. I use yarn to install - Thanks to https://dev.to/kolide/how-to-migrate-a-rails-6-app-from-sass-rails-to-cssbundling-rails-4l41 for that clean up
- added the following to app/assets/stylesheets/application.bootstrap.scss thanks to https://fontawesome.com/docs/web/use-with/scss (after checking what css was being compiled to determine fa-font-path and added regular and v4-shims after looking in the folder)
```
$fa-font-path: '/assets';
@import '@fortawesome/fontawesome-free/scss/fontawesome';
@import '@fortawesome/fontawesome-free/scss/brands';
@import '@fortawesome/fontawesome-free/scss/solid';
@import '@fortawesome/fontawesome-free/scss/regular';
@import '@fortawesome/fontawesome-free/scss/v4-shims';
```
My testing is with development and checking puiblic/assets after `bin/rake tmp:clear assets:clobber assets:precompile`

FYI, my package.json looks like:
```
{
  "name": "app",
  "private": "true",
  "dependencies": {
    "@fortawesome/fontawesome-free": "^6.1.0",
    "@hotwired/stimulus": "^3.0.1",
    "@hotwired/turbo-rails": "^7.1.1",
    "@popperjs/core": "^2.11.4",
    "bootstrap": "^5.1.3",
    "bootstrap-icons": "^1.8.1",
    "esbuild": "^0.14.27",
    "sass": "^1.49.9"
  },
  "scripts": {
    "build:css": "sass ./app/assets/stylesheets/application.bootstrap.scss ./app/assets/builds/application.css --no-source-map --load-path=node_modules",
    "build": "esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds"
  }
}
```
and my Procfile.dev has the following (I also have Procfile.watch that excludes web for running seperately whilst debugging under rubymine):
```
web: bin/rails server -p 3040 -b 0.0.0.0
js: yarn build --watch
css: yarn build:css --watch
```

**Comment by pezholio** [comment]
I'm still unclear as to how this works in practice. I have a file in `app/assets/images`, and I'm referencing it in my sass like so:

```
background: #fff url("image.png") repeat-x;
```

But my image is 404ing. Is there a step I'm missing here?

**Comment by rromanchuk** [comment]
cssbundling + import maps has made my deployment about a million times less complex  but trying to come up with a better workflow for a similar issue. For context, i need to explain how i serve rails requests.

- All requests start at CloudFront, SSL termination completes here
- CloudFront then routes the request to any number of origins with separate request/response behaviors
  - Any path matching `/assets*`, requests are routed to S3 origin, with its own caching behavior.  The request path is the exact key path of the bucket
  - Specialty paths like `robots.txt` `apple-app-site-association` are handled directly at the edge 
  - Paths matching `/cable` ALB(80) -> EC2(8080) -> anycable
  - All other request are sent to ALB(80) -> EC2(80) -> nginx -> puma. 

So that means in my rails configuration there is no separate CDN configuration, it's entirely host agnostic. A request with `/assets` has a different origin and cache setup than `/api`

The entire production frontend deploy
```bash
# deploy.sh
bin/rails assets:precompile
aws s3 sync public/assets s3://app-www/assets --storage-class INTELLIGENT_TIERING --cache-control max-age=31536000
```

```javascript
// app/assets/config/manifest.js

//= link_tree ../images
//= link_tree ../../javascript .js
//= link_tree ../../../vendor/javascript .js

//= link_tree ../builds
//= link favicon/browserconfig.xml
//= link foo.pdf
```
app/assets/stylesheets/application.sass.scss
```scss
// app/assets/stylesheets/application.sass.scss

// this is scss in node_modules, yarn:build:css handles this fine
// and application.css in ../build is ready for sprockets
@import 'bootstrap/scss/bootstrap'; 

// app/assets/stylesheets/coderay.css
// A relative boring plain old css file. yarn:build:css handles this fine, BUT
// this is already valid css, and compiled 'as is', but sprockets knows nothing about
// this asset. I could declare a //= link in manifest but will have no digest knowledge
@import 'coderay.css';
```
package.json 
```json
{
  "name": "app",
  "private": "true",
  "dependencies": {
    "bootstrap": "^5.1.3",
    "sass": "^1.50.1"
  },
  "scripts": {
    "build:css": "sass ./app/assets/stylesheets/application.sass.scss ./app/assets/builds/application.css --no-source-map --load-path=node_modules"
  }
}
```

I was thinking of maybe modifying my deploy by creating something like `vendor/static`  and adding `aws s3 sync vendor/static s3://app-www/assets/static`, basically hiding it from sprockets, as the "wysiwyg never-digested folder".  Obvious drawbacks: no tag helpers allowed for these assets, and figuring out how to serve locally.

```html
<link href="/assets/static/big_annoying_never_modified.min.css" media="screen" rel="stylesheet" />
```

```scss
@font-face {
  font-family: "annoying-font";
  src: url("/assets/static/annoying.eot");
}
```

For my case, does **any** pre/post-processing make sense at all? I can already completely offload these steps. Instead of wasting my CPU cycles, cloudfront can handle the gzip/brotli, and for digesting, i have full control over request/response to the origin with accurate etags. It's not like the past where i'm serving  both rails and assets acting as the origin behind old school CDN, fumbling my way through nginx cache control headers.

TDLR: Can I just turn off digesting, and just use known relative paths, with or without tag helpers, for the rest of my life?

**Comment by rromanchuk** [comment]
*And by not worry, I mean, wouldn't it be totally reasonable to have cloudfront just hit the origin and query application.css/js for status after 30 seconds (or zero, who cares)  and just let it do what it does best vs brute forcing a miss?

**Comment by GregSmith92** [comment]
@ianheggie Thanks for your set up help. Works great for me in development, but once pushed to Heroku I get errors in my logs like: `ActionController::RoutingError (No route matches [GET] "/assets/fa-solid-900.ttf"):` I actually get this for any 3rd party assets I try to load in production, other than scss files. 

Any ideas on why this might be?

My set up is the same as yours, other than my css script: 
`"build:css": "sass ./app/assets/stylesheets/application.sass.scss ./app/assets/builds/application.css --no-source-map --load-path=node_modules" `

**Comment by deepj** [comment]
@GregSmith92 

You might be in the same situation as I was. I see you're trying to use font-awesome.

In my case I use Propshaft, but the following wouldn't be different from Sprocket

**config/initializers/assets.rb**

```ruby
Rails.application.config.assets.excluded_paths += [Rails.root.join('app/assets/stylesheets'), Rails.root.join('app/javascript')]

# Add additional assets to the asset load path.
Rails.application.config.assets.paths << Rails.root.join('node_modules/@fortawesome/fontawesome-free/webfonts')
```

**application.css.scss**

```scss
$fa-font-path: '';
@import '@fortawesome/fontawesome-free/scss/fontawesome';
@import '@fortawesome/fontawesome-free/scss/regular';
@import '@fortawesome/fontawesome-free/scss/solid';
```

**Comment by GregSmith92** [comment]
@deepj 

Using `$fa-font-path: '';` does not work for me in development. 
Both `$fa-font-path: '/assets/@fortawesome/fontawesome-free/webfonts';` and `$fa-font-path: '/assets';` do work in development, but neither in production.

I don't understand why!! In both environments the assets are in the right place:
```
Dir.entries("public/assets/@fortawesome/fontawesome-free/webfonts")
=> 
["fa-solid-900-a0cc38b88839387e4451bb1ebdd9ecd821b2df0f7fcd5b26df75630f4171ee32.ttf.gz",
 "fa-brands-400-d6e9a2e4cad853a5a88711678db47de7456f36b30923f8350f55c41434809ba8.ttf.gz",
 "fa-v4compatibility-8351eb008a6fa9eca28be682c28af28e47d9d668e34128fb789072aa90d5c2e7.ttf",
 "fa-solid-900-addc97d14257b43232b89194f73bd3b862007d5eedcb4569362b8f26356d8db3.woff2",
 "fa-v4compatibility-8dc02461354e5f9713549bb76c84c6aa45a23c728534a8ce658a66a045f1cb76.woff2",
 "fa-brands-400-d6e9a2e4cad853a5a88711678db47de7456f36b30923f8350f55c41434809ba8.ttf",
 "fa-regular-400-79a39b18a5524be800ab200fbedebf7f737a316f01b874fe42b005fda10a6f11.ttf.gz",
 "fa-brands-400-e624f952dec1ac1e2673205a87513cab83c4a0d187b08528a5ff0c36d9b1e090.woff2",
 "fa-regular-400-6919b47939790fc2ab662fd09b22907c53f32d9a817eed0782e2fb3e7af24b5b.woff2",
 "..",
 "fa-v4compatibility-8351eb008a6fa9eca28be682c28af28e47d9d668e34128fb789072aa90d5c2e7.ttf.gz",
 "fa-regular-400-79a39b18a5524be800ab200fbedebf7f737a316f01b874fe42b005fda10a6f11.ttf",
 "fa-solid-900-a0cc38b88839387e4451bb1ebdd9ecd821b2df0f7fcd5b26df75630f4171ee32.ttf",
 "."]
```

**Comment by GregSmith92** [comment]
Incase someone stumbles upon this, I removed all fontawesome bootstrap refrences from application.scss, manifest.js and config/assets.rb and instead added `import "@fortawesome/fontawesome-free/js/all"` to my application.js and it now works fine in both environemnts. I'm sure there is a solution for just using scss but I couldn't find it.

**Comment by chloerei** [comment]
To fix fontawesome problem:

config/initializers/assets.rb

```ruby
Rails.application.config.assets.paths << Rails.root.join('node_modules/@fortawesome/fontawesome-free/webfonts')
```

application.css.scss

```scss
$fa-font-path: ".";

@import "@fortawesome/fontawesome-free/scss/fontawesome.scss";
@import "@fortawesome/fontawesome-free/scss/solid.scss";
```

**Comment by jasonfb** [comment]
note: The solution that was brought into rails was to automatically pick up `url` references in your SCSS files. As of Rails 7.0/7.1 with the recent versions of this gem, you should no longer be using `asset-path` or `asset-url` in your SCSS files, instead, just use `url` and the built-in helpers will convert them to the pipeline paths.

note that if you seem to not getting your `url` markers in your CSS, triple check that the file name in `app/assets/images/` matches what you have in your CSS.

**Comment by goulvench** [comment]
Thanks for the helpful hints above! I tried various combinations before finding something that works, so I'm sharing my setup when **using FontAwesome as scss using cssbundling+propshaft**:

`app/assets/stylesheets/fontawesome.scss`
```scss
$fa-font-path: ""; // or "."
@import "@fortawesome/fontawesome-free/scss/fontawesome";
@import "@fortawesome/fontawesome-free/scss/brands";
@import "@fortawesome/fontawesome-free/scss/solid";
@import "@fortawesome/fontawesome-free/scss/regular";
```

`config/initializers/assets.rb`
```ruby
Rails.application.config.assets.version = "1.0"
Rails.application.config.assets.paths << Rails.root.join("node_modules/@fortawesome/fontawesome-free/webfonts")
```

I have **no `app/assets/config/manifest.js`** because it's only used by Sprockets, Propshaft doesn't care about this file.

`package.json`
```json
"scripts": {
  "build": "esbuild app/javascript/*.* --bundle --sourcemap --format=esm --outdir=app/assets/builds --public-path=/assets",
  "build:css": "sass ./app/assets/stylesheets/:./app/assets/builds/ --no-source-map --load-path=node_modules"
}
```
I'm telling sass to compile the `stylesheets` folder (instead of specifying the stylesheet name) because I chose to generate `application.css` and `fontawesome.css` separately, since FontAwesome is bound to change much less often. The line is shorter and more flexible as well.

Gem versions:
```yaml
rails: 7.1.3.2
css-bundling: 1.4.0
js-bundling: 1.3.0
propshaft: 0.8.0
```

If you want to see what is generated, run `bin/rails assets:clobber && bin/rails assets:precompile` and examine the contents of the `public/assets/` folder.   
When you're happy with the results, run `bin/rails assets:clobber` otherwise the compiled assets will take precedence and you won't see the CSS and JS changes you make.
